# Generated by Django 2.2.3 on 2019-07-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milouser',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
